name: "Fast Forward Forks"
on:
  workflow_dispatch:
  schedule:
  - cron: "15 * * * *"

jobs:
  ff_mp:
    name: Fast Forward Macports
    runs-on: ubuntu-latest
    steps:
    - name: Merge upstream
      uses: rohrwerkzeuge/upstream-updates@1.0.0
      with:
        repo: 'macports-ports'
        op-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        branch: 'master'
