on:
  workflow_dispatch:

jobs:
  ff_mp:
    runs-on: ubuntu-latest
    steps:  
    - name: Fast Forward Macports
      uses: markemer/upstream-updates@main
      with:
        repo: 'markemer/macports'
        op-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
  
