on:
  workflow_dispatch:

jobs:
  ff_mp:
    name: Fast Forward Macports
    runs-on: ubuntu-latest
    steps:  
    - name: Get Repositories
      uses: markemer/upstream-updates@main
      with:
        repo: 'macports-ports'
        op-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
  
